# Change these first
owner: WeArePanda # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: We are Panda
    url: https://wearepanda.co.uk/
  - name: Bunkr
    url: https://bunkr.co.uk/
  - name: Test Site
    url: http://lpcic.co.uk/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Uptime
  logoUrl: https://wearepanda.co.uk/wp-content/uploads/2024/05/wap-panda-logo-twotone2.png
  name: We are Panda Status
  introTitle: "Website downtime monitor"
  introMessage: Using real-time data with Slck notifications
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
